-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.notebook_archives (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  notebook_id uuid,
  cycle_number integer NOT NULL DEFAULT 1,
  words_count integer NOT NULL DEFAULT 0,
  completed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notebook_archives_pkey PRIMARY KEY (id),
  CONSTRAINT notebook_archives_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notebook_archives_notebook_id_fkey FOREIGN KEY (notebook_id) REFERENCES public.notebooks(id)
);
CREATE TABLE public.notebooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  language text NOT NULL,
  language_code text NOT NULL,
  notebook_level USER-DEFINED NOT NULL DEFAULT 'bronze'::notebook_level_enum,
  words_per_day integer NOT NULL DEFAULT 20,
  review_interval_days integer NOT NULL DEFAULT 14,
  is_active boolean NOT NULL DEFAULT true,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notebooks_pkey PRIMARY KEY (id),
  CONSTRAINT notebooks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_history (
  id text NOT NULL,
  user_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['daily_words'::text, 'progress_reminder'::text, 'review_ready'::text, 'streak_protection'::text])),
  title text NOT NULL,
  body text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  scheduled_at timestamp with time zone,
  sent_at timestamp with time zone,
  read_at timestamp with time zone,
  clicked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_history_pkey PRIMARY KEY (id),
  CONSTRAINT notification_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notebook_id uuid,
  page_number integer NOT NULL,
  date_created date NOT NULL DEFAULT CURRENT_DATE,
  target_round USER-DEFINED NOT NULL DEFAULT '1'::round_number,
  words_count integer NOT NULL DEFAULT 0,
  is_completed boolean NOT NULL DEFAULT false,
  next_review_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_unlocked boolean NOT NULL DEFAULT false,
  unlock_date date,
  page_review_date date,
  page_current_round integer DEFAULT 1 CHECK (page_current_round >= 1 AND page_current_round <= 4),
  page_status text DEFAULT 'pending'::text CHECK (page_status = ANY (ARRAY['pending'::text, 'active'::text, 'completed'::text, 'migrated'::text])),
  page_completion_date date,
  review_date timestamp with time zone,
  status text DEFAULT 'accumulating'::text,
  current_round integer DEFAULT 1 CHECK (current_round >= 1 AND current_round <= 4),
  context_title text,
  context_source text,
  context_description text,
  context_theme text,
  CONSTRAINT pages_pkey PRIMARY KEY (id),
  CONSTRAINT pages_notebook_id_fkey FOREIGN KEY (notebook_id) REFERENCES public.notebooks(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  display_name text,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subscription_status text NOT NULL DEFAULT 'free'::text CHECK (subscription_status = ANY (ARRAY['free'::text, 'trial'::text, 'weekly'::text, 'monthly'::text, 'yearly'::text])),
  subscription_expires_at timestamp with time zone,
  subscription_transaction_id text,
  streak_count integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  total_words_added integer NOT NULL DEFAULT 0,
  total_words_mastered integer NOT NULL DEFAULT 0,
  last_activity_date date DEFAULT CURRENT_DATE,
  onboarding_completed boolean NOT NULL DEFAULT false,
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  streak_miss_count integer DEFAULT 0 CHECK (streak_miss_count >= 0),
  subscription_activated_at timestamp with time zone,
  trial_started_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  word_id uuid NOT NULL,
  round USER-DEFINED NOT NULL,
  reviewed_at timestamp with time zone NOT NULL DEFAULT now(),
  remembered boolean NOT NULL,
  next_review_date date,
  response_time_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.words(id)
);
CREATE TABLE public.subscription_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  status USER-DEFINED NOT NULL,
  expires_at timestamp with time zone,
  transaction_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_logs_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_notification_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  enable_notifications boolean DEFAULT true,
  enable_daily_reminders boolean DEFAULT true,
  enable_progress_reminders boolean DEFAULT true,
  enable_review_reminders boolean DEFAULT true,
  enable_streak_protection boolean DEFAULT true,
  daily_reminder_time time without time zone DEFAULT '14:00:00'::time without time zone,
  progress_reminder_time time without time zone DEFAULT '17:00:00'::time without time zone,
  review_reminder_time time without time zone DEFAULT '19:00:00'::time without time zone,
  streak_reminder_time time without time zone DEFAULT '21:00:00'::time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notification_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.words (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notebook_id uuid NOT NULL,
  word text NOT NULL,
  translation text NOT NULL,
  example_sentence text,
  notes text,
  current_round integer NOT NULL DEFAULT 1,
  is_mastered boolean NOT NULL DEFAULT false,
  review_date date NOT NULL,
  last_reviewed date,
  times_reviewed integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  page_id uuid,
  meaning text,
  position_in_page integer DEFAULT 1,
  status USER-DEFINED DEFAULT 'learning'::word_status,
  source_notebook_id uuid,
  original_page_id uuid,
  difficulty_tag text NOT NULL DEFAULT 'NORMAL'::text CHECK (difficulty_tag = ANY (ARRAY['NORMAL'::text, 'EXTREMELY_HARD'::text, 'MASTER_LEVEL'::text, 'LEGENDARY'::text])),
  cycle_count integer NOT NULL DEFAULT 0,
  word_type text DEFAULT 'unknown'::text CHECK (word_type = ANY (ARRAY['verb'::text, 'noun'::text, 'adjective'::text, 'adverb'::text, 'preposition'::text, 'conjunction'::text, 'interjection'::text, 'pronoun'::text, 'article'::text, 'other'::text, 'unknown'::text])),
  sentence_meaning text,
  sentence_bold text,
  meaning_bold text,
  is_archived boolean DEFAULT false,
  archived_notebook_id uuid,
  archived_at timestamp with time zone,
  archive_cycle_number integer DEFAULT 1,
  CONSTRAINT words_pkey PRIMARY KEY (id),
  CONSTRAINT words_notebook_id_fkey FOREIGN KEY (notebook_id) REFERENCES public.notebooks(id),
  CONSTRAINT words_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.pages(id),
  CONSTRAINT words_source_notebook_id_fkey FOREIGN KEY (source_notebook_id) REFERENCES public.notebooks(id),
  CONSTRAINT words_original_page_id_fkey FOREIGN KEY (original_page_id) REFERENCES public.pages(id)
);