-- Add sentence_meaning column to words table for AI-generated sentence translations
-- This stores the translation/meaning of the example_sentence in the user's native language

ALTER TABLE words 
ADD COLUMN sentence_meaning TEXT NULL;

-- Add comment to document the column purpose
COMMENT ON COLUMN words.sentence_meaning IS 'Translation of example_sentence to user''s native language, generated by AI';

-- Optional: Add index if we plan to search by sentence meanings (probably not needed)
-- CREATE INDEX idx_words_sentence_meaning ON words USING gin(to_tsvector('english', sentence_meaning));

-- Verify the column was added
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'words' 
AND column_name = 'sentence_meaning';